### ISSUE TITLE
Add new methods to IPagination

### ISSUE THREAD

**Issue by bes422** [jdi-testing/jdi-2.0#3]
Would be great to have next default methods in IPagination:

- isNextEnabled() / isNextPresent()
- isPreviousEnabled() / isPreviousPresent()
- isFirstEnabled() / isFirstPresent()
- isLastEnabled() / isLastPresent()
- getSelectedPage() - return selected page index

**Comment by RomanIovlev** [comment]
I agree on getSelectedPage but don't think to add is...Present as default Pagination methods. I won't overcompensate this interface. Also isEnabled method for all items will be good so I think better to do one method with params for this. Will be in next release
